//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace old_phone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int blog_id { get; set; }
        public string blog_name { get; set; }
        public string blog_author { get; set; }
        public string blog_link { get; set; }
        public System.DateTime blog_time { get; set; }
        public string blog_img { get; set; }
    }
}
