//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace old_phone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int cart_id { get; set; }
        public int account_id { get; set; }
        public int variant_id { get; set; }
        public int cart_count { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Variant_Phone Variant_Phone { get; set; }
    }
}
