//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace old_phone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int detail_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> variant_id { get; set; }
        public string detail_name { get; set; }
        public int detail_count { get; set; }
        public long detail_total_price { get; set; }
    
        public virtual Variant_Phone Variant_Phone { get; set; }
        public virtual Order_ Order_ { get; set; }
    }
}
