//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace old_phone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_()
        {
            this.Details = new HashSet<Detail>();
        }
    
        public int order_id { get; set; }
        public Nullable<int> account_id { get; set; }
        public Nullable<int> hotline_id { get; set; }
        public System.DateTime order_buy_time { get; set; }
        public System.DateTime order_rec_time { get; set; }
        public string order_type_pay { get; set; }
        public string order_state { get; set; }
        public long order_total_price { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail> Details { get; set; }
        public virtual Hotline Hotline { get; set; }
    }
}
