//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace old_phone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int product_id { get; set; }
        public string phone_chip { get; set; }
        public string phone_screen_size { get; set; }
        public string phone_front_cam { get; set; }
        public string phone_behind_cam { get; set; }
        public int phone_battery { get; set; }
        public string phone_system { get; set; }
        public string phone_charging_port { get; set; }
        public int phone_sim_card { get; set; }
        public bool phone_nfc { get; set; }
        public string phone_ear_phone { get; set; }
        public bool phone_memory_card { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
