//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace old_phone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int sale_id { get; set; }
        public string sale_name { get; set; }
        public System.DateTime sale_start { get; set; }
        public System.DateTime sale_end { get; set; }
        public Nullable<int> variant_id { get; set; }
    
        public virtual Variant_Phone Variant_Phone { get; set; }
    }
}
