//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace old_phone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variant_Phone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Variant_Phone()
        {
            this.Carts = new HashSet<Cart>();
            this.Carts1 = new HashSet<Cart>();
            this.Details = new HashSet<Detail>();
            this.Details1 = new HashSet<Detail>();
            this.Sales = new HashSet<Sale>();
        }
    
        public int variant_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public int variant_ph_ram { get; set; }
        public int variant_ph_rom { get; set; }
        public string variant_ph_color { get; set; }
        public long variant_ph_org_price { get; set; }
        public long variant_ph_new_price { get; set; }
        public long variant_ph_final_price { get; set; }
        public string variant_ph_img { get; set; }
        public string variant_ph_state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail> Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail> Details1 { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
